In [38]:
import pandas as pd

data = {
"Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
"Age": [25, 30, None, 28, 35],
"Salary": [30000, 45000, 50000, None, 60000],
"City": ["Delhi", "Mumbai", None, "Pune", "Delhi"],
"Email": ["rahul@gamil.com", None, "priya@gmail.com", None, "rohit@gmail.com"],
"Phone": [8547154296, 5968421879, 8475147726, 9584572106, 9948751426]
}

df = pd.DataFrame(data)

print(df)

    Name   Age   Salary    City            Email       Phone
0  Rahul  25.0  30000.0   Delhi  rahul@gamil.com  8547154296
1   Aman  30.0  45000.0  Mumbai              NaN  5968421879
2  Priya   NaN  50000.0     NaN  priya@gmail.com  8475147726
3   Neha  28.0      NaN    Pune              NaN  9584572106
4  Rohit  35.0  60000.0   Delhi  rohit@gmail.com  9948751426

In [39]:
df.isnull() # df.isna()

    Name    Age  Salary   City  Email  Phone
0  False  False   False  False  False  False
1  False  False   False  False   True  False
2  False   True   False   True  False  False
3  False  False    True  False   True  False
4  False  False   False  False  False  False

In [40]:
df.isna()

    Name    Age  Salary   City  Email  Phone
0  False  False   False  False  False  False
1  False  False   False  False   True  False
2  False   True   False   True  False  False
3  False  False    True  False   True  False
4  False  False   False  False  False  False

In [41]:
df.isnull().sum()

Name      0
Age       1
Salary    1
City      1
Email     2
Phone     0
dtype: int64

In [42]:
df.isnull().sum().sum()

np.int64(5)

In [53]:
# find rows having missing values
df[df.isnull().any(axis = 1)]

    Name   Age   Salary    City            Email       Phone
1   Aman  30.0  45000.0  Mumbai              NaN  5968421879
2  Priya   NaN  50000.0     NaN  priya@gmail.com  8475147726
3   Neha  28.0      NaN    Pune              NaN  9584572106

In [44]:
df[df.notnull().all(axis = 1)]

    Name   Age   Salary   City            Email       Phone
0  Rahul  25.0  30000.0  Delhi  rahul@gamil.com  8547154296
4  Rohit  35.0  60000.0  Delhi  rohit@gmail.com  9948751426

In [49]:
new_df = df.dropna()

print(new_df)

    Name   Age   Salary   City            Email       Phone
0  Rahul  25.0  30000.0  Delhi  rahul@gamil.com  8547154296
4  Rohit  35.0  60000.0  Delhi  rohit@gmail.com  9948751426

In [46]:
df

    Name   Age   Salary    City            Email       Phone
0  Rahul  25.0  30000.0   Delhi  rahul@gamil.com  8547154296
1   Aman  30.0  45000.0  Mumbai              NaN  5968421879
2  Priya   NaN  50000.0     NaN  priya@gmail.com  8475147726
3   Neha  28.0      NaN    Pune              NaN  9584572106
4  Rohit  35.0  60000.0   Delhi  rohit@gmail.com  9948751426

In [58]:
df.isnull().values.any(axis = 1)

array([False,  True,  True,  True, False])

In [56]:
df.isnull().any()

Name      False
Age        True
Salary     True
City       True
Email      True
Phone     False
dtype: bool