In [3]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\skr04.VICTUS-HP\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\skr04.VICTUS-HP\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\skr04.VICTUS-HP\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\skr04.VICTUS-HP\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\skr04.VICTUS-HP\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

In [49]:
marks = pd.Series([1, 2, 3, 4, 5, 6]) # custome indexing index=["a", "b", "c", "d", "e", "f"]

# print(marks)
# print(marks[3])
# print(marks.head())
# print(marks.tail())
# print(marks.mean())
# print(marks.sum())
# print(marks.min())
print(marks.max())

print(marks.shape)

6
(6,)

In [59]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 22, 35, 32],
    'City': ['New York', 'Paris', 'London', 'Tokyo'],
}
# df = pd.DataFrame(data)
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 270.0 bytes

             Age
count   4.000000
mean   29.250000
std     5.619905
min    22.000000
25%    26.500000
50%    30.000000
75%    32.750000
max    35.000000

In [35]:
Age = data["Age"][2]
print("Age: ", Age)

Age:  35

In [7]:
df

    Name  Age      City
0   John   28  New York
1   Anna   22     Paris
2  Peter   35    London
3  Linda   32     Tokyo

In [45]:
print(data["Name"])
print("\n")

df

['John', 'Anna', 'Peter', 'Linda']

    Name  Age      City
0   John   28  New York
1   Anna   22     Paris
2  Peter   35    London
3  Linda   32     Tokyo

In [14]:
print(df[df['Age'] > 30])

    Name  Age    City
2  Peter   35  London
3  Linda   32   Tokyo

In [15]:
df.shape

(4, 3)

In [28]:
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [17]:
print(df['Age'].describe())

count     4.000000
mean     29.250000
std       5.619905
min      22.000000
25%      26.500000
50%      30.000000
75%      32.750000
max      35.000000
Name: Age, dtype: float64

In [19]:
df['Status'] = ['Active', 'Inactive', 'Active', 'Active']

In [20]:
df

    Name  Age      City    Status
0   John   28  New York    Active
1   Anna   22     Paris  Inactive
2  Peter   35    London    Active
3  Linda   32     Tokyo    Active

In [ ]:
print("\nCount by Status:")
print(df.groupby('Status').size())

<bound method NDFrame.describe of     Name  Age      City
0   John   28  New York
1   Anna   22     Paris
2  Peter   35    London
3  Linda   32     Tokyo>