In [45]:
import pandas as pd

In [46]:
df = pd.read_csv(r"C:\Users\skr04.VICTUS-HP\Documents\pandas_loc_iloc_filtering_assignment.csv")
df

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
1,1003,Aditya,39,Male,Bangalore,IT,40280,3.7,77,10,66
2,1004,Nikhil,27,Female,Chandigarh,Marketing,56893,7.0,62,1,75
3,1005,Tanya,34,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,39,Female,Bangalore,Marketing,75447,3.7,53,9,96
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
19,1021,Tanya,30,Female,Bangalore,Finance,87177,2.3,59,2,86
20,1022,Aarav,39,Male,Jaipur,HR,28942,1.5,85,1,79
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
22,1024,Shreya,39,Male,Jaipur,Sales,89993,12.2,57,2,71
23,1025,Kriti,34,Female,Pune,Sales,89213,13.0,48,11,71
24,1026,Vivaan,33,Male,Chandigarh,Finance,60591,3.3,79,8,73
25,1027,Meera,26,Male,Pune,Sales,37880,6.9,100,9,71
26,1028,Vivaan,38,Male,Delhi,IT,49798,6.4,75,4,90
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
28,1030,Meera,38,Male,Chandigarh,Sales,52890,4.8,48,10,99
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,23,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
33,1035,Yash,39,Male,Delhi,IT,94307,4.3,67,2,80
34,1036,Ishita,30,Female,Mumbai,Sales,29025,10.2,80,5,71
35,1037,Kabir,29,Male,Delhi,IT,63697,4.6,58,12,86
36,1038,Rahul,29,Female,Jaipur,Sales,34658,1.8,72,5,67
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
38,1040,Arjun,23,Male,Chandigarh,HR,76393,8.9,54,7,73
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,27,Female,Bangalore,Finance,37099,14.5,62,6,97
44,1046,Simran,38,Male,Pune,IT,62237,3.1,61,1,71
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
48,1050,Rahul,34,Male,Chandigarh,Sales,67446,6.4,98,1,84
49,1051,Priya,27,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,39,Female,Mumbai,Sales,80383,4.0,86,12,65
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82
56,1058,Aman,36,Female,Chandigarh,HR,85654,1.6,63,4,82
57,1059,Neha,31,Male,Jaipur,IT,47769,3.9,89,3,78
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89
59,1061,Varun,21,Female,Jaipur,Sales,28772,14.2,64,7,91

In [47]:
df.loc[0:10]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
1,1003,Aditya,39,Male,Bangalore,IT,40280,3.7,77,10,66
2,1004,Nikhil,27,Female,Chandigarh,Marketing,56893,7.0,62,1,75
3,1005,Tanya,34,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99

In [48]:
df.loc[5: 14]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,39,Female,Bangalore,Marketing,75447,3.7,53,9,96
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84

In [49]:
df.iloc[10:19]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,39,Female,Bangalore,Marketing,75447,3.7,53,9,96
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77

In [50]:
df[["Name", "Department"]]

      Name Department
0    Sneha    Finance
1   Aditya         IT
2   Nikhil  Marketing
3    Tanya    Finance
4   Simran    Finance
5   Aditya  Marketing
6    Priya         IT
7   Ishita    Finance
8   Simran  Marketing
9   Vivaan    Finance
10   Rahul      Sales
11  Ananya  Marketing
12  Aditya         HR
13    Aman         IT
14   Meera         IT
15   Sneha         HR
16    Yash         IT
17  Vivaan         IT
18   Kabir         HR
19   Tanya    Finance
20   Aarav         HR
21  Aditya         IT
22  Shreya      Sales
23   Kriti      Sales
24  Vivaan    Finance
25   Meera      Sales
26  Vivaan         IT
27  Vivaan         IT
28   Meera      Sales
29  Vivaan         IT
30    Aman         IT
31    Yash  Marketing
32  Ananya    Finance
33    Yash         IT
34  Ishita      Sales
35   Kabir         IT
36   Rahul      Sales
37   Aarav    Finance
38   Arjun         HR
39  Vivaan         IT
40  Nikhil         HR
41   Aarav    Finance
42  Simran         HR
43   Aarav    Finance
44  Simran         IT
45    Yash    Finance
46  Vivaan  Marketing
47   Kriti    Finance
48   Rahul      Sales
49   Priya  Marketing
50    Riya         IT
51   Karan         IT
52   Meera      Sales
53   Arjun         HR
54   Kabir  Marketing
55  Nikhil      Sales
56    Aman         HR
57    Neha         IT
58  Aditya    Finance
59   Varun      Sales

In [51]:
df[["Name", "City", "Salary", "Performance_Score"]]

      Name        City  Salary  Performance_Score
0    Sneha       Delhi   57256                 51
1   Aditya   Bangalore   40280                 77
2   Nikhil  Chandigarh   56893                 62
3    Tanya        Pune   56221                 66
4   Simran        Pune   33695                 79
5   Aditya        Pune   53203                 47
6    Priya      Mumbai   64434                 98
7   Ishita      Mumbai   50431                 60
8   Simran  Chandigarh   70504                 94
9   Vivaan   Bangalore   55653                 81
10   Rahul   Bangalore   62718                 92
11  Ananya   Bangalore   75447                 53
12  Aditya       Delhi   83333                 69
13    Aman      Jaipur   62973                 66
14   Meera   Bangalore   93612                 77
15   Sneha      Jaipur   77009                 79
16    Yash   Bangalore   75576                 98
17  Vivaan      Jaipur   91699                 93
18   Kabir      Jaipur   83461                 79
19   Tanya   Bangalore   87177                 59
20   Aarav      Jaipur   28942                 85
21  Aditya        Pune   64500                 58
22  Shreya      Jaipur   89993                 57
23   Kriti        Pune   89213                 48
24  Vivaan  Chandigarh   60591                 79
25   Meera        Pune   37880                100
26  Vivaan       Delhi   49798                 75
27  Vivaan   Bangalore   62760                 95
28   Meera  Chandigarh   52890                 48
29  Vivaan       Delhi   93909                 78
30    Aman      Mumbai   58828                 81
31    Yash   Bangalore   62179                 90
32  Ananya      Mumbai   69441                 49
33    Yash       Delhi   94307                 67
34  Ishita      Mumbai   29025                 80
35   Kabir       Delhi   63697                 58
36   Rahul      Jaipur   34658                 72
37   Aarav      Mumbai   85912                 72
38   Arjun  Chandigarh   76393                 54
39  Vivaan        Pune   55535                 87
40  Nikhil      Jaipur   49299                 96
41   Aarav  Chandigarh   60527                 95
42  Simran   Bangalore   88332                 97
43   Aarav   Bangalore   37099                 62
44  Simran        Pune   62237                 61
45    Yash        Pune   43157                 81
46  Vivaan       Delhi   75739                 87
47   Kriti  Chandigarh   81528                 89
48   Rahul  Chandigarh   67446                 98
49   Priya   Bangalore   88946                 88
50    Riya  Chandigarh   71933                 93
51   Karan      Mumbai   60092                 84
52   Meera      Mumbai   80383                 86
53   Arjun      Mumbai   34582                 99
54   Kabir  Chandigarh   86008                 91
55  Nikhil      Mumbai   61972                 98
56    Aman  Chandigarh   85654                 63
57    Neha      Jaipur   47769                 89
58  Aditya   Bangalore   82496                 98
59   Varun      Jaipur   28772                 64

In [52]:
df.loc[10:20, ["Name", "Salary"]]

      Name  Salary
10   Rahul   62718
11  Ananya   75447
12  Aditya   83333
13    Aman   62973
14   Meera   93612
15   Sneha   77009
16    Yash   75576
17  Vivaan   91699
18   Kabir   83461
19   Tanya   87177
20   Aarav   28942

In [53]:
df.iloc[5:16, 1:6]

      Name  Age  Gender        City Department
5   Aditya   38  Female        Pune  Marketing
6    Priya   23  Female      Mumbai         IT
7   Ishita   32    Male      Mumbai    Finance
8   Simran   29    Male  Chandigarh  Marketing
9   Vivaan   31    Male   Bangalore    Finance
10   Rahul   36    Male   Bangalore      Sales
11  Ananya   39  Female   Bangalore  Marketing
12  Aditya   22    Male       Delhi         HR
13    Aman   29    Male      Jaipur         IT
14   Meera   26  Female   Bangalore         IT
15   Sneha   37    Male      Jaipur         HR

In [54]:
df[df["Salary"] > 60000]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,39,Female,Bangalore,Marketing,75447,3.7,53,9,96
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
19,1021,Tanya,30,Female,Bangalore,Finance,87177,2.3,59,2,86
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
22,1024,Shreya,39,Male,Jaipur,Sales,89993,12.2,57,2,71
23,1025,Kriti,34,Female,Pune,Sales,89213,13.0,48,11,71
24,1026,Vivaan,33,Male,Chandigarh,Finance,60591,3.3,79,8,73
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
31,1033,Yash,23,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
33,1035,Yash,39,Male,Delhi,IT,94307,4.3,67,2,80
35,1037,Kabir,29,Male,Delhi,IT,63697,4.6,58,12,86
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
38,1040,Arjun,23,Male,Chandigarh,HR,76393,8.9,54,7,73
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
44,1046,Simran,38,Male,Pune,IT,62237,3.1,61,1,71
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
48,1050,Rahul,34,Male,Chandigarh,Sales,67446,6.4,98,1,84
49,1051,Priya,27,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,39,Female,Mumbai,Sales,80383,4.0,86,12,65
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82
56,1058,Aman,36,Female,Chandigarh,HR,85654,1.6,63,4,82
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89

In [55]:
df[df["Age"] < 25]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,23,Female,Bangalore,Marketing,62179,3.5,90,6,80
38,1040,Arjun,23,Male,Chandigarh,HR,76393,8.9,54,7,73
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
59,1061,Varun,21,Female,Jaipur,Sales,28772,14.2,64,7,91

In [56]:
df[df["Performance_Score"] > 80]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
20,1022,Aarav,39,Male,Jaipur,HR,28942,1.5,85,1,79
25,1027,Meera,26,Male,Pune,Sales,37880,6.9,100,9,71
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,23,Female,Bangalore,Marketing,62179,3.5,90,6,80
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
48,1050,Rahul,34,Male,Chandigarh,Sales,67446,6.4,98,1,84
49,1051,Priya,27,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,39,Female,Mumbai,Sales,80383,4.0,86,12,65
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82
57,1059,Neha,31,Male,Jaipur,IT,47769,3.9,89,3,78
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89

In [57]:
df[df["Experience_Years"] > 5]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
2,1004,Nikhil,27,Female,Chandigarh,Marketing,56893,7.0,62,1,75
3,1005,Tanya,34,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
22,1024,Shreya,39,Male,Jaipur,Sales,89993,12.2,57,2,71
23,1025,Kriti,34,Female,Pune,Sales,89213,13.0,48,11,71
25,1027,Meera,26,Male,Pune,Sales,37880,6.9,100,9,71
26,1028,Vivaan,38,Male,Delhi,IT,49798,6.4,75,4,90
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
34,1036,Ishita,30,Female,Mumbai,Sales,29025,10.2,80,5,71
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
38,1040,Arjun,23,Male,Chandigarh,HR,76393,8.9,54,7,73
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,27,Female,Bangalore,Finance,37099,14.5,62,6,97
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
48,1050,Rahul,34,Male,Chandigarh,Sales,67446,6.4,98,1,84
49,1051,Priya,27,Female,Bangalore,Marketing,88946,6.9,88,4,97
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82
59,1061,Varun,21,Female,Jaipur,Sales,28772,14.2,64,7,91

In [58]:
df[df["Projects_Completed"] > 7]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
1,1003,Aditya,39,Male,Bangalore,IT,40280,3.7,77,10,66
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,39,Female,Bangalore,Marketing,75447,3.7,53,9,96
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
23,1025,Kriti,34,Female,Pune,Sales,89213,13.0,48,11,71
24,1026,Vivaan,33,Male,Chandigarh,Finance,60591,3.3,79,8,73
25,1027,Meera,26,Male,Pune,Sales,37880,6.9,100,9,71
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
28,1030,Meera,38,Male,Chandigarh,Sales,52890,4.8,48,10,99
35,1037,Kabir,29,Male,Delhi,IT,63697,4.6,58,12,86
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
52,1054,Meera,39,Female,Mumbai,Sales,80383,4.0,86,12,65
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82

In [59]:
df[df["Attendance_Percent"] > 80]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,39,Female,Bangalore,Marketing,75447,3.7,53,9,96
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
19,1021,Tanya,30,Female,Bangalore,Finance,87177,2.3,59,2,86
26,1028,Vivaan,38,Male,Delhi,IT,49798,6.4,75,4,90
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
28,1030,Meera,38,Male,Chandigarh,Sales,52890,4.8,48,10,99
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
35,1037,Kabir,29,Male,Delhi,IT,63697,4.6,58,12,86
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
43,1045,Aarav,27,Female,Bangalore,Finance,37099,14.5,62,6,97
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85
48,1050,Rahul,34,Male,Chandigarh,Sales,67446,6.4,98,1,84
49,1051,Priya,27,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82
56,1058,Aman,36,Female,Chandigarh,HR,85654,1.6,63,4,82
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89
59,1061,Varun,21,Female,Jaipur,Sales,28772,14.2,64,7,91

In [60]:
df[df["Department"] == "IT"]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
1,1003,Aditya,39,Male,Bangalore,IT,40280,3.7,77,10,66
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
26,1028,Vivaan,38,Male,Delhi,IT,49798,6.4,75,4,90
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
33,1035,Yash,39,Male,Delhi,IT,94307,4.3,67,2,80
35,1037,Kabir,29,Male,Delhi,IT,63697,4.6,58,12,86
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
44,1046,Simran,38,Male,Pune,IT,62237,3.1,61,1,71
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
57,1059,Neha,31,Male,Jaipur,IT,47769,3.9,89,3,78

In [61]:
df[df["City"] == "Delhi"]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
26,1028,Vivaan,38,Male,Delhi,IT,49798,6.4,75,4,90
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
33,1035,Yash,39,Male,Delhi,IT,94307,4.3,67,2,80
35,1037,Kabir,29,Male,Delhi,IT,63697,4.6,58,12,86
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85

In [62]:
df[df["Gender"] == "Female"]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
2,1004,Nikhil,27,Female,Chandigarh,Marketing,56893,7.0,62,1,75
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
11,1013,Ananya,39,Female,Bangalore,Marketing,75447,3.7,53,9,96
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
19,1021,Tanya,30,Female,Bangalore,Finance,87177,2.3,59,2,86
23,1025,Kriti,34,Female,Pune,Sales,89213,13.0,48,11,71
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
31,1033,Yash,23,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
34,1036,Ishita,30,Female,Mumbai,Sales,29025,10.2,80,5,71
36,1038,Rahul,29,Female,Jaipur,Sales,34658,1.8,72,5,67
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
43,1045,Aarav,27,Female,Bangalore,Finance,37099,14.5,62,6,97
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
49,1051,Priya,27,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
52,1054,Meera,39,Female,Mumbai,Sales,80383,4.0,86,12,65
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82
56,1058,Aman,36,Female,Chandigarh,HR,85654,1.6,63,4,82
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89
59,1061,Varun,21,Female,Jaipur,Sales,28772,14.2,64,7,91

In [63]:
df[(df["Salary"] > 70000) & (df["Performance_Score"] > 80)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
49,1051,Priya,27,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
52,1054,Meera,39,Female,Mumbai,Sales,80383,4.0,86,12,65
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89

In [64]:
df[(df["Age"] > 30) & (df["Experience_Years"] > 5)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
3,1005,Tanya,34,Male,Pune,Finance,56221,14.4,66,2,70
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
22,1024,Shreya,39,Male,Jaipur,Sales,89993,12.2,57,2,71
23,1025,Kriti,34,Female,Pune,Sales,89213,13.0,48,11,71
26,1028,Vivaan,38,Male,Delhi,IT,49798,6.4,75,4,90
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85
48,1050,Rahul,34,Male,Chandigarh,Sales,67446,6.4,98,1,84
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82

In [65]:
df[(df["Department"] == "IT") & (df["Salary"] > 60000)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
33,1035,Yash,39,Male,Delhi,IT,94307,4.3,67,2,80
35,1037,Kabir,29,Male,Delhi,IT,63697,4.6,58,12,86
44,1046,Simran,38,Male,Pune,IT,62237,3.1,61,1,71
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94

In [66]:
df[(df["City"] == "Delhi") & (df["Performance_Score"] > 80)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85

In [67]:
df[(df["Salary"] < 40000) | (df["Performance_Score"] > 90)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
20,1022,Aarav,39,Male,Jaipur,HR,28942,1.5,85,1,79
25,1027,Meera,26,Male,Pune,Sales,37880,6.9,100,9,71
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
34,1036,Ishita,30,Female,Mumbai,Sales,29025,10.2,80,5,71
36,1038,Rahul,29,Female,Jaipur,Sales,34658,1.8,72,5,67
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,27,Female,Bangalore,Finance,37099,14.5,62,6,97
48,1050,Rahul,34,Male,Chandigarh,Sales,67446,6.4,98,1,84
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89
59,1061,Varun,21,Female,Jaipur,Sales,28772,14.2,64,7,91

In [68]:
df[(df["City"] == "Mumbai") | (df["City"] == "Pune")]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
3,1005,Tanya,34,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
23,1025,Kriti,34,Female,Pune,Sales,89213,13.0,48,11,71
25,1027,Meera,26,Male,Pune,Sales,37880,6.9,100,9,71
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
34,1036,Ishita,30,Female,Mumbai,Sales,29025,10.2,80,5,71
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
44,1046,Simran,38,Male,Pune,IT,62237,3.1,61,1,71
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,39,Female,Mumbai,Sales,80383,4.0,86,12,65
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82

In [69]:
df[(df["Department"] == "HR") | (df["Department"] == "Finance")] # df[df["Department"].isin("HR", "Finance"")]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
3,1005,Tanya,34,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
19,1021,Tanya,30,Female,Bangalore,Finance,87177,2.3,59,2,86
20,1022,Aarav,39,Male,Jaipur,HR,28942,1.5,85,1,79
24,1026,Vivaan,33,Male,Chandigarh,Finance,60591,3.3,79,8,73
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
38,1040,Arjun,23,Male,Chandigarh,HR,76393,8.9,54,7,73
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,27,Female,Bangalore,Finance,37099,14.5,62,6,97
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
56,1058,Aman,36,Female,Chandigarh,HR,85654,1.6,63,4,82
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89

In [70]:
df[(df["Age"] < 25) | (df["Experience_Years"] > 10)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
3,1005,Tanya,34,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
22,1024,Shreya,39,Male,Jaipur,Sales,89993,12.2,57,2,71
23,1025,Kriti,34,Female,Pune,Sales,89213,13.0,48,11,71
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,23,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
34,1036,Ishita,30,Female,Mumbai,Sales,29025,10.2,80,5,71
38,1040,Arjun,23,Male,Chandigarh,HR,76393,8.9,54,7,73
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,27,Female,Bangalore,Finance,37099,14.5,62,6,97
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82
59,1061,Varun,21,Female,Jaipur,Sales,28772,14.2,64,7,91

In [71]:
df[df["City"] != "Delhi"]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
1,1003,Aditya,39,Male,Bangalore,IT,40280,3.7,77,10,66
2,1004,Nikhil,27,Female,Chandigarh,Marketing,56893,7.0,62,1,75
3,1005,Tanya,34,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,39,Female,Bangalore,Marketing,75447,3.7,53,9,96
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
19,1021,Tanya,30,Female,Bangalore,Finance,87177,2.3,59,2,86
20,1022,Aarav,39,Male,Jaipur,HR,28942,1.5,85,1,79
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
22,1024,Shreya,39,Male,Jaipur,Sales,89993,12.2,57,2,71
23,1025,Kriti,34,Female,Pune,Sales,89213,13.0,48,11,71
24,1026,Vivaan,33,Male,Chandigarh,Finance,60591,3.3,79,8,73
25,1027,Meera,26,Male,Pune,Sales,37880,6.9,100,9,71
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
28,1030,Meera,38,Male,Chandigarh,Sales,52890,4.8,48,10,99
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,23,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
34,1036,Ishita,30,Female,Mumbai,Sales,29025,10.2,80,5,71
36,1038,Rahul,29,Female,Jaipur,Sales,34658,1.8,72,5,67
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
38,1040,Arjun,23,Male,Chandigarh,HR,76393,8.9,54,7,73
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,27,Female,Bangalore,Finance,37099,14.5,62,6,97
44,1046,Simran,38,Male,Pune,IT,62237,3.1,61,1,71
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
48,1050,Rahul,34,Male,Chandigarh,Sales,67446,6.4,98,1,84
49,1051,Priya,27,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,39,Female,Mumbai,Sales,80383,4.0,86,12,65
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82
56,1058,Aman,36,Female,Chandigarh,HR,85654,1.6,63,4,82
57,1059,Neha,31,Male,Jaipur,IT,47769,3.9,89,3,78
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89
59,1061,Varun,21,Female,Jaipur,Sales,28772,14.2,64,7,91

In [72]:
df[df["Department"] != "Sales"]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
1,1003,Aditya,39,Male,Bangalore,IT,40280,3.7,77,10,66
2,1004,Nikhil,27,Female,Chandigarh,Marketing,56893,7.0,62,1,75
3,1005,Tanya,34,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
8,1010,Simran,29,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
11,1013,Ananya,39,Female,Bangalore,Marketing,75447,3.7,53,9,96
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
19,1021,Tanya,30,Female,Bangalore,Finance,87177,2.3,59,2,86
20,1022,Aarav,39,Male,Jaipur,HR,28942,1.5,85,1,79
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
24,1026,Vivaan,33,Male,Chandigarh,Finance,60591,3.3,79,8,73
26,1028,Vivaan,38,Male,Delhi,IT,49798,6.4,75,4,90
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,23,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
33,1035,Yash,39,Male,Delhi,IT,94307,4.3,67,2,80
35,1037,Kabir,29,Male,Delhi,IT,63697,4.6,58,12,86
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
38,1040,Arjun,23,Male,Chandigarh,HR,76393,8.9,54,7,73
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,22,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,27,Female,Bangalore,Finance,37099,14.5,62,6,97
44,1046,Simran,38,Male,Pune,IT,62237,3.1,61,1,71
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
49,1051,Priya,27,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
53,1055,Arjun,34,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,35,Female,Chandigarh,Marketing,86008,9.4,91,9,92
56,1058,Aman,36,Female,Chandigarh,HR,85654,1.6,63,4,82
57,1059,Neha,31,Male,Jaipur,IT,47769,3.9,89,3,78
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89

In [73]:
# df[(df["Salary"] >= 40000) & (df["Salary"] <= 70000)] 
df[df["Salary"].between(40000, 70000)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
1,1003,Aditya,39,Male,Bangalore,IT,40280,3.7,77,10,66
2,1004,Nikhil,27,Female,Chandigarh,Marketing,56893,7.0,62,1,75
3,1005,Tanya,34,Male,Pune,Finance,56221,14.4,66,2,70
5,1007,Aditya,38,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,32,Male,Mumbai,Finance,50431,8.2,60,3,94
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,36,Male,Bangalore,Sales,62718,2.5,92,9,99
13,1015,Aman,29,Male,Jaipur,IT,62973,11.6,66,2,83
21,1023,Aditya,22,Male,Pune,IT,64500,10.2,58,9,73
24,1026,Vivaan,33,Male,Chandigarh,Finance,60591,3.3,79,8,73
26,1028,Vivaan,38,Male,Delhi,IT,49798,6.4,75,4,90
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
28,1030,Meera,38,Male,Chandigarh,Sales,52890,4.8,48,10,99
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,23,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
35,1037,Kabir,29,Male,Delhi,IT,63697,4.6,58,12,86
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,34,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
44,1046,Simran,38,Male,Pune,IT,62237,3.1,61,1,71
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
48,1050,Rahul,34,Male,Chandigarh,Sales,67446,6.4,98,1,84
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82
57,1059,Neha,31,Male,Jaipur,IT,47769,3.9,89,3,78

In [74]:
df[df["Performance_Score"].between(70, 90)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
1,1003,Aditya,39,Male,Bangalore,IT,40280,3.7,77,10,66
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,37,Male,Jaipur,HR,77009,11.6,79,9,65
18,1020,Kabir,36,Female,Jaipur,HR,83461,14.5,79,12,77
20,1022,Aarav,39,Male,Jaipur,HR,28942,1.5,85,1,79
24,1026,Vivaan,33,Male,Chandigarh,Finance,60591,3.3,79,8,73
26,1028,Vivaan,38,Male,Delhi,IT,49798,6.4,75,4,90
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,23,Female,Bangalore,Marketing,62179,3.5,90,6,80
34,1036,Ishita,30,Female,Mumbai,Sales,29025,10.2,80,5,71
36,1038,Rahul,29,Female,Jaipur,Sales,34658,1.8,72,5,67
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
49,1051,Priya,27,Female,Bangalore,Marketing,88946,6.9,88,4,97
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,39,Female,Mumbai,Sales,80383,4.0,86,12,65
57,1059,Neha,31,Male,Jaipur,IT,47769,3.9,89,3,78

In [75]:
df[((df["City"] == "Delhi") | (df["City"] == "Mumbai")) & (df["Salary"] > 55000)]
# df[(df["City"].isin(["Delhi", "Mumbai"])) & (df["Salary"] > 55000)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,24,Male,Delhi,Finance,57256,2.5,51,11,99
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
12,1014,Aditya,22,Male,Delhi,HR,83333,9.1,69,7,94
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
32,1034,Ananya,33,Female,Mumbai,Finance,69441,14.0,49,1,94
33,1035,Yash,39,Male,Delhi,IT,94307,4.3,67,2,80
35,1037,Kabir,29,Male,Delhi,IT,63697,4.6,58,12,86
37,1039,Aarav,31,Male,Mumbai,Finance,85912,8.5,72,9,65
46,1048,Vivaan,34,Male,Delhi,Marketing,75739,6.8,87,6,85
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,39,Female,Mumbai,Sales,80383,4.0,86,12,65
55,1057,Nikhil,35,Female,Mumbai,Sales,61972,11.4,98,11,82

In [76]:
df[((df["Department"] == "IT") | (df["Department"] == "Finance")) & (df["Performance_Score"] > 75)]
# df[(df["City"].isin(["Delhi", "Mumbai"])) & (df["Salary"] > 55000)]

,Employee_ID,Name,Age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
1,1003,Aditya,39,Male,Bangalore,IT,40280,3.7,77,10,66
4,1006,Simran,24,Female,Pune,Finance,33695,11.1,79,2,89
6,1008,Priya,23,Female,Mumbai,IT,64434,7.1,98,6,75
9,1011,Vivaan,31,Male,Bangalore,Finance,55653,13.7,81,12,85
14,1016,Meera,26,Female,Bangalore,IT,93612,11.5,77,2,84
16,1018,Yash,31,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,28,Male,Jaipur,IT,91699,12.3,93,9,73
24,1026,Vivaan,33,Male,Chandigarh,Finance,60591,3.3,79,8,73
27,1029,Vivaan,26,Female,Bangalore,IT,62760,13.9,95,8,83
29,1031,Vivaan,31,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,23,Male,Mumbai,IT,58828,6.4,81,4,67
39,1041,Vivaan,30,Female,Pune,IT,55535,10.4,87,2,87
41,1043,Aarav,26,Female,Chandigarh,Finance,60527,4.4,95,12,71
45,1047,Yash,34,Female,Pune,Finance,43157,6.1,81,4,81
47,1049,Kriti,24,Female,Chandigarh,Finance,81528,5.2,89,5,73
50,1052,Riya,26,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,27,Male,Mumbai,IT,60092,14.8,84,2,94
57,1059,Neha,31,Male,Jaipur,IT,47769,3.9,89,3,78
58,1060,Aditya,34,Female,Bangalore,Finance,82496,1.4,98,7,89

In [111]:
df.sort_values("Experience_Years", ascending = False) # accessing the columns data by sorting

,Employee_ID,Name,Fin_age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
51,1053,Karan,52,Male,Mumbai,IT,60092,14.8,84,2,94
40,1042,Nikhil,59,Male,Jaipur,HR,49299,14.7,96,3,91
18,1020,Kabir,61,Female,Jaipur,HR,83461,14.5,79,12,77
43,1045,Aarav,52,Female,Bangalore,Finance,37099,14.5,62,6,97
3,1005,Tanya,59,Male,Pune,Finance,56221,14.4,66,2,70
59,1061,Varun,46,Female,Jaipur,Sales,28772,14.2,64,7,91
32,1034,Ananya,58,Female,Mumbai,Finance,69441,14.0,49,1,94
27,1029,Vivaan,51,Female,Bangalore,IT,62760,13.9,95,8,83
29,1031,Vivaan,56,Female,Delhi,IT,93909,13.8,78,3,68
9,1011,Vivaan,56,Male,Bangalore,Finance,55653,13.7,81,12,85
16,1018,Yash,56,Male,Bangalore,IT,75576,13.2,98,5,80
23,1025,Kriti,59,Female,Pune,Sales,89213,13.0,48,11,71
8,1010,Simran,54,Male,Chandigarh,Marketing,70504,12.7,94,1,79
17,1019,Vivaan,53,Male,Jaipur,IT,91699,12.3,93,9,73
22,1024,Shreya,64,Male,Jaipur,Sales,89993,12.2,57,2,71
15,1017,Sneha,62,Male,Jaipur,HR,77009,11.6,79,9,65
13,1015,Aman,54,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,51,Female,Bangalore,IT,93612,11.5,77,2,84
55,1057,Nikhil,60,Female,Mumbai,Sales,61972,11.4,98,11,82
4,1006,Simran,49,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,63,Female,Pune,Marketing,53203,10.7,47,11,79
39,1041,Vivaan,55,Female,Pune,IT,55535,10.4,87,2,87
21,1023,Aditya,47,Male,Pune,IT,64500,10.2,58,9,73
34,1036,Ishita,55,Female,Mumbai,Sales,29025,10.2,80,5,71
54,1056,Kabir,60,Female,Chandigarh,Marketing,86008,9.4,91,9,92
12,1014,Aditya,47,Male,Delhi,HR,83333,9.1,69,7,94
38,1040,Arjun,48,Male,Chandigarh,HR,76393,8.9,54,7,73
53,1055,Arjun,59,Female,Mumbai,HR,34582,8.6,99,2,94
37,1039,Aarav,56,Male,Mumbai,Finance,85912,8.5,72,9,65
7,1009,Ishita,57,Male,Mumbai,Finance,50431,8.2,60,3,94
6,1008,Priya,48,Female,Mumbai,IT,64434,7.1,98,6,75
2,1004,Nikhil,52,Female,Chandigarh,Marketing,56893,7.0,62,1,75
25,1027,Meera,51,Male,Pune,Sales,37880,6.9,100,9,71
49,1051,Priya,52,Female,Bangalore,Marketing,88946,6.9,88,4,97
46,1048,Vivaan,59,Male,Delhi,Marketing,75739,6.8,87,6,85
26,1028,Vivaan,63,Male,Delhi,IT,49798,6.4,75,4,90
48,1050,Rahul,59,Male,Chandigarh,Sales,67446,6.4,98,1,84
30,1032,Aman,48,Male,Mumbai,IT,58828,6.4,81,4,67
45,1047,Yash,59,Female,Pune,Finance,43157,6.1,81,4,81
42,1044,Simran,47,Male,Bangalore,HR,88332,5.6,97,4,79
47,1049,Kriti,49,Female,Chandigarh,Finance,81528,5.2,89,5,73
28,1030,Meera,63,Male,Chandigarh,Sales,52890,4.8,48,10,99
35,1037,Kabir,54,Male,Delhi,IT,63697,4.6,58,12,86
41,1043,Aarav,51,Female,Chandigarh,Finance,60527,4.4,95,12,71
33,1035,Yash,64,Male,Delhi,IT,94307,4.3,67,2,80
52,1054,Meera,64,Female,Mumbai,Sales,80383,4.0,86,12,65
57,1059,Neha,56,Male,Jaipur,IT,47769,3.9,89,3,78
11,1013,Ananya,64,Female,Bangalore,Marketing,75447,3.7,53,9,96
1,1003,Aditya,64,Male,Bangalore,IT,40280,3.7,77,10,66
31,1033,Yash,48,Female,Bangalore,Marketing,62179,3.5,90,6,80
24,1026,Vivaan,58,Male,Chandigarh,Finance,60591,3.3,79,8,73
44,1046,Simran,63,Male,Pune,IT,62237,3.1,61,1,71
0,1002,Sneha,49,Male,Delhi,Finance,57256,2.5,51,11,99
10,1012,Rahul,61,Male,Bangalore,Sales,62718,2.5,92,9,99
19,1021,Tanya,55,Female,Bangalore,Finance,87177,2.3,59,2,86
50,1052,Riya,51,Female,Chandigarh,IT,71933,1.9,93,4,84
36,1038,Rahul,54,Female,Jaipur,Sales,34658,1.8,72,5,67
56,1058,Aman,61,Female,Chandigarh,HR,85654,1.6,63,4,82
20,1022,Aarav,64,Male,Jaipur,HR,28942,1.5,85,1,79
58,1060,Aditya,59,Female,Bangalore,Finance,82496,1.4,98,7,89

In [112]:
df["Fin_age"] = df["Fin_age"] + 5 # update the exsisting columns
df

,Employee_ID,Name,Fin_age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,54,Male,Delhi,Finance,57256,2.5,51,11,99
1,1003,Aditya,69,Male,Bangalore,IT,40280,3.7,77,10,66
2,1004,Nikhil,57,Female,Chandigarh,Marketing,56893,7.0,62,1,75
3,1005,Tanya,64,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,54,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,68,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,53,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,62,Male,Mumbai,Finance,50431,8.2,60,3,94
8,1010,Simran,59,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,61,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,66,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,69,Female,Bangalore,Marketing,75447,3.7,53,9,96
12,1014,Aditya,52,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,59,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,56,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,67,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,61,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,58,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,66,Female,Jaipur,HR,83461,14.5,79,12,77
19,1021,Tanya,60,Female,Bangalore,Finance,87177,2.3,59,2,86
20,1022,Aarav,69,Male,Jaipur,HR,28942,1.5,85,1,79
21,1023,Aditya,52,Male,Pune,IT,64500,10.2,58,9,73
22,1024,Shreya,69,Male,Jaipur,Sales,89993,12.2,57,2,71
23,1025,Kriti,64,Female,Pune,Sales,89213,13.0,48,11,71
24,1026,Vivaan,63,Male,Chandigarh,Finance,60591,3.3,79,8,73
25,1027,Meera,56,Male,Pune,Sales,37880,6.9,100,9,71
26,1028,Vivaan,68,Male,Delhi,IT,49798,6.4,75,4,90
27,1029,Vivaan,56,Female,Bangalore,IT,62760,13.9,95,8,83
28,1030,Meera,68,Male,Chandigarh,Sales,52890,4.8,48,10,99
29,1031,Vivaan,61,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,53,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,53,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,63,Female,Mumbai,Finance,69441,14.0,49,1,94
33,1035,Yash,69,Male,Delhi,IT,94307,4.3,67,2,80
34,1036,Ishita,60,Female,Mumbai,Sales,29025,10.2,80,5,71
35,1037,Kabir,59,Male,Delhi,IT,63697,4.6,58,12,86
36,1038,Rahul,59,Female,Jaipur,Sales,34658,1.8,72,5,67
37,1039,Aarav,61,Male,Mumbai,Finance,85912,8.5,72,9,65
38,1040,Arjun,53,Male,Chandigarh,HR,76393,8.9,54,7,73
39,1041,Vivaan,60,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,64,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,56,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,52,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,57,Female,Bangalore,Finance,37099,14.5,62,6,97
44,1046,Simran,68,Male,Pune,IT,62237,3.1,61,1,71
45,1047,Yash,64,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,64,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,54,Female,Chandigarh,Finance,81528,5.2,89,5,73
48,1050,Rahul,64,Male,Chandigarh,Sales,67446,6.4,98,1,84
49,1051,Priya,57,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,56,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,57,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,69,Female,Mumbai,Sales,80383,4.0,86,12,65
53,1055,Arjun,64,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,65,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,65,Female,Mumbai,Sales,61972,11.4,98,11,82
56,1058,Aman,66,Female,Chandigarh,HR,85654,1.6,63,4,82
57,1059,Neha,61,Male,Jaipur,IT,47769,3.9,89,3,78
58,1060,Aditya,64,Female,Bangalore,Finance,82496,1.4,98,7,89
59,1061,Varun,51,Female,Jaipur,Sales,28772,14.2,64,7,91

In [108]:
df.rename(columns={"Age": "Max_age"}, inplace= True) # change the exsisting columns name and inplace to change the permanent name

In [113]:
df

,Employee_ID,Name,Fin_age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,54,Male,Delhi,Finance,57256,2.5,51,11,99
1,1003,Aditya,69,Male,Bangalore,IT,40280,3.7,77,10,66
2,1004,Nikhil,57,Female,Chandigarh,Marketing,56893,7.0,62,1,75
3,1005,Tanya,64,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,54,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,68,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,53,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,62,Male,Mumbai,Finance,50431,8.2,60,3,94
8,1010,Simran,59,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,61,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,66,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,69,Female,Bangalore,Marketing,75447,3.7,53,9,96
12,1014,Aditya,52,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,59,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,56,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,67,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,61,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,58,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,66,Female,Jaipur,HR,83461,14.5,79,12,77
19,1021,Tanya,60,Female,Bangalore,Finance,87177,2.3,59,2,86
20,1022,Aarav,69,Male,Jaipur,HR,28942,1.5,85,1,79
21,1023,Aditya,52,Male,Pune,IT,64500,10.2,58,9,73
22,1024,Shreya,69,Male,Jaipur,Sales,89993,12.2,57,2,71
23,1025,Kriti,64,Female,Pune,Sales,89213,13.0,48,11,71
24,1026,Vivaan,63,Male,Chandigarh,Finance,60591,3.3,79,8,73
25,1027,Meera,56,Male,Pune,Sales,37880,6.9,100,9,71
26,1028,Vivaan,68,Male,Delhi,IT,49798,6.4,75,4,90
27,1029,Vivaan,56,Female,Bangalore,IT,62760,13.9,95,8,83
28,1030,Meera,68,Male,Chandigarh,Sales,52890,4.8,48,10,99
29,1031,Vivaan,61,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,53,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,53,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,63,Female,Mumbai,Finance,69441,14.0,49,1,94
33,1035,Yash,69,Male,Delhi,IT,94307,4.3,67,2,80
34,1036,Ishita,60,Female,Mumbai,Sales,29025,10.2,80,5,71
35,1037,Kabir,59,Male,Delhi,IT,63697,4.6,58,12,86
36,1038,Rahul,59,Female,Jaipur,Sales,34658,1.8,72,5,67
37,1039,Aarav,61,Male,Mumbai,Finance,85912,8.5,72,9,65
38,1040,Arjun,53,Male,Chandigarh,HR,76393,8.9,54,7,73
39,1041,Vivaan,60,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,64,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,56,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,52,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,57,Female,Bangalore,Finance,37099,14.5,62,6,97
44,1046,Simran,68,Male,Pune,IT,62237,3.1,61,1,71
45,1047,Yash,64,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,64,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,54,Female,Chandigarh,Finance,81528,5.2,89,5,73
48,1050,Rahul,64,Male,Chandigarh,Sales,67446,6.4,98,1,84
49,1051,Priya,57,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,56,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,57,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,69,Female,Mumbai,Sales,80383,4.0,86,12,65
53,1055,Arjun,64,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,65,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,65,Female,Mumbai,Sales,61972,11.4,98,11,82
56,1058,Aman,66,Female,Chandigarh,HR,85654,1.6,63,4,82
57,1059,Neha,61,Male,Jaipur,IT,47769,3.9,89,3,78
58,1060,Aditya,64,Female,Bangalore,Finance,82496,1.4,98,7,89
59,1061,Varun,51,Female,Jaipur,Sales,28772,14.2,64,7,91

In [115]:
# df.drop(Columns_name, axis = 1 "for cloumns only")
df.drop("Fin_age", axis = 1) # df.drop(["Fin_age", "Gender"], axis = 1)

,Employee_ID,Name,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,Male,Delhi,Finance,57256,2.5,51,11,99
1,1003,Aditya,Male,Bangalore,IT,40280,3.7,77,10,66
2,1004,Nikhil,Female,Chandigarh,Marketing,56893,7.0,62,1,75
3,1005,Tanya,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,Male,Mumbai,Finance,50431,8.2,60,3,94
8,1010,Simran,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,Female,Bangalore,Marketing,75447,3.7,53,9,96
12,1014,Aditya,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,Female,Jaipur,HR,83461,14.5,79,12,77
19,1021,Tanya,Female,Bangalore,Finance,87177,2.3,59,2,86
20,1022,Aarav,Male,Jaipur,HR,28942,1.5,85,1,79
21,1023,Aditya,Male,Pune,IT,64500,10.2,58,9,73
22,1024,Shreya,Male,Jaipur,Sales,89993,12.2,57,2,71
23,1025,Kriti,Female,Pune,Sales,89213,13.0,48,11,71
24,1026,Vivaan,Male,Chandigarh,Finance,60591,3.3,79,8,73
25,1027,Meera,Male,Pune,Sales,37880,6.9,100,9,71
26,1028,Vivaan,Male,Delhi,IT,49798,6.4,75,4,90
27,1029,Vivaan,Female,Bangalore,IT,62760,13.9,95,8,83
28,1030,Meera,Male,Chandigarh,Sales,52890,4.8,48,10,99
29,1031,Vivaan,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,Female,Mumbai,Finance,69441,14.0,49,1,94
33,1035,Yash,Male,Delhi,IT,94307,4.3,67,2,80
34,1036,Ishita,Female,Mumbai,Sales,29025,10.2,80,5,71
35,1037,Kabir,Male,Delhi,IT,63697,4.6,58,12,86
36,1038,Rahul,Female,Jaipur,Sales,34658,1.8,72,5,67
37,1039,Aarav,Male,Mumbai,Finance,85912,8.5,72,9,65
38,1040,Arjun,Male,Chandigarh,HR,76393,8.9,54,7,73
39,1041,Vivaan,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,Female,Bangalore,Finance,37099,14.5,62,6,97
44,1046,Simran,Male,Pune,IT,62237,3.1,61,1,71
45,1047,Yash,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,Female,Chandigarh,Finance,81528,5.2,89,5,73
48,1050,Rahul,Male,Chandigarh,Sales,67446,6.4,98,1,84
49,1051,Priya,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,Female,Mumbai,Sales,80383,4.0,86,12,65
53,1055,Arjun,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,Female,Mumbai,Sales,61972,11.4,98,11,82
56,1058,Aman,Female,Chandigarh,HR,85654,1.6,63,4,82
57,1059,Neha,Male,Jaipur,IT,47769,3.9,89,3,78
58,1060,Aditya,Female,Bangalore,Finance,82496,1.4,98,7,89
59,1061,Varun,Female,Jaipur,Sales,28772,14.2,64,7,91

In [116]:
df.drop(2) #for row only give index like df.drop(3) / df.drop([2, 3])

,Employee_ID,Name,Fin_age,Gender,City,Department,Salary,Experience_Years,Performance_Score,Projects_Completed,Attendance_Percent
0,1002,Sneha,54,Male,Delhi,Finance,57256,2.5,51,11,99
1,1003,Aditya,69,Male,Bangalore,IT,40280,3.7,77,10,66
3,1005,Tanya,64,Male,Pune,Finance,56221,14.4,66,2,70
4,1006,Simran,54,Female,Pune,Finance,33695,11.1,79,2,89
5,1007,Aditya,68,Female,Pune,Marketing,53203,10.7,47,11,79
6,1008,Priya,53,Female,Mumbai,IT,64434,7.1,98,6,75
7,1009,Ishita,62,Male,Mumbai,Finance,50431,8.2,60,3,94
8,1010,Simran,59,Male,Chandigarh,Marketing,70504,12.7,94,1,79
9,1011,Vivaan,61,Male,Bangalore,Finance,55653,13.7,81,12,85
10,1012,Rahul,66,Male,Bangalore,Sales,62718,2.5,92,9,99
11,1013,Ananya,69,Female,Bangalore,Marketing,75447,3.7,53,9,96
12,1014,Aditya,52,Male,Delhi,HR,83333,9.1,69,7,94
13,1015,Aman,59,Male,Jaipur,IT,62973,11.6,66,2,83
14,1016,Meera,56,Female,Bangalore,IT,93612,11.5,77,2,84
15,1017,Sneha,67,Male,Jaipur,HR,77009,11.6,79,9,65
16,1018,Yash,61,Male,Bangalore,IT,75576,13.2,98,5,80
17,1019,Vivaan,58,Male,Jaipur,IT,91699,12.3,93,9,73
18,1020,Kabir,66,Female,Jaipur,HR,83461,14.5,79,12,77
19,1021,Tanya,60,Female,Bangalore,Finance,87177,2.3,59,2,86
20,1022,Aarav,69,Male,Jaipur,HR,28942,1.5,85,1,79
21,1023,Aditya,52,Male,Pune,IT,64500,10.2,58,9,73
22,1024,Shreya,69,Male,Jaipur,Sales,89993,12.2,57,2,71
23,1025,Kriti,64,Female,Pune,Sales,89213,13.0,48,11,71
24,1026,Vivaan,63,Male,Chandigarh,Finance,60591,3.3,79,8,73
25,1027,Meera,56,Male,Pune,Sales,37880,6.9,100,9,71
26,1028,Vivaan,68,Male,Delhi,IT,49798,6.4,75,4,90
27,1029,Vivaan,56,Female,Bangalore,IT,62760,13.9,95,8,83
28,1030,Meera,68,Male,Chandigarh,Sales,52890,4.8,48,10,99
29,1031,Vivaan,61,Female,Delhi,IT,93909,13.8,78,3,68
30,1032,Aman,53,Male,Mumbai,IT,58828,6.4,81,4,67
31,1033,Yash,53,Female,Bangalore,Marketing,62179,3.5,90,6,80
32,1034,Ananya,63,Female,Mumbai,Finance,69441,14.0,49,1,94
33,1035,Yash,69,Male,Delhi,IT,94307,4.3,67,2,80
34,1036,Ishita,60,Female,Mumbai,Sales,29025,10.2,80,5,71
35,1037,Kabir,59,Male,Delhi,IT,63697,4.6,58,12,86
36,1038,Rahul,59,Female,Jaipur,Sales,34658,1.8,72,5,67
37,1039,Aarav,61,Male,Mumbai,Finance,85912,8.5,72,9,65
38,1040,Arjun,53,Male,Chandigarh,HR,76393,8.9,54,7,73
39,1041,Vivaan,60,Female,Pune,IT,55535,10.4,87,2,87
40,1042,Nikhil,64,Male,Jaipur,HR,49299,14.7,96,3,91
41,1043,Aarav,56,Female,Chandigarh,Finance,60527,4.4,95,12,71
42,1044,Simran,52,Male,Bangalore,HR,88332,5.6,97,4,79
43,1045,Aarav,57,Female,Bangalore,Finance,37099,14.5,62,6,97
44,1046,Simran,68,Male,Pune,IT,62237,3.1,61,1,71
45,1047,Yash,64,Female,Pune,Finance,43157,6.1,81,4,81
46,1048,Vivaan,64,Male,Delhi,Marketing,75739,6.8,87,6,85
47,1049,Kriti,54,Female,Chandigarh,Finance,81528,5.2,89,5,73
48,1050,Rahul,64,Male,Chandigarh,Sales,67446,6.4,98,1,84
49,1051,Priya,57,Female,Bangalore,Marketing,88946,6.9,88,4,97
50,1052,Riya,56,Female,Chandigarh,IT,71933,1.9,93,4,84
51,1053,Karan,57,Male,Mumbai,IT,60092,14.8,84,2,94
52,1054,Meera,69,Female,Mumbai,Sales,80383,4.0,86,12,65
53,1055,Arjun,64,Female,Mumbai,HR,34582,8.6,99,2,94
54,1056,Kabir,65,Female,Chandigarh,Marketing,86008,9.4,91,9,92
55,1057,Nikhil,65,Female,Mumbai,Sales,61972,11.4,98,11,82
56,1058,Aman,66,Female,Chandigarh,HR,85654,1.6,63,4,82
57,1059,Neha,61,Male,Jaipur,IT,47769,3.9,89,3,78
58,1060,Aditya,64,Female,Bangalore,Finance,82496,1.4,98,7,89
59,1061,Varun,51,Female,Jaipur,Sales,28772,14.2,64,7,91