In [2]:
import os
import pandas as pd

In [54]:
df = pd.read_csv(r"C:\Users\skr04.VICTUS-HP\Documents\employees.csv")
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [6]:
 # Print how many rows and columns it has.
print(df.shape)

(1000, 8)

In [12]:
 # Print the list of column names.
print(df.columns)

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='str')

In [18]:
 # Use info() and write down which columns have missing values.
df.info

<bound method DataFrame.info of     First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389
..         ...     ...         ...             ...     ...      ...
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                   NaN
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
995             False          Distribution
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[1000 rows x 8 columns]>

In [19]:
 # Load the file again, but import only First Name, Team and Salary
df[["First Name", "Team", "Salary"]]

    First Name                  Team  Salary
0      Douglas             Marketing   97308
1       Thomas                   NaN   61933
2        Maria               Finance  130590
3        Jerry               Finance  138705
4        Larry       Client Services  101004
..         ...                   ...     ...
995      Henry          Distribution  132483
996    Phillip               Finance   42392
997    Russell               Product   96914
998      Larry  Business Development   60500
999     Albert                 Sales  129949

[1000 rows x 3 columns]

In [60]:
# Print the first 5 and last 5 values.
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [59]:
df.tail()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [58]:
 # Print the value at index label 10
df.iloc[0:10]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering
9,Frances,Female,8/8/2002,6:51 AM,139852,7.524,True,Business Development

In [57]:
# Print every 4th value from position 3 to position 20
df.iloc[3:20:4]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product

In [61]:
# Create a new Series of monthly salary (Salary divided by 12).
df["Monthly Salary"] = df["Salary"] / 12

In [62]:
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Monthly Salary
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,8109.000000
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,5161.083333
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,10882.500000
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,11558.750000
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,8417.000000
...,...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution,11040.250000
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance,3532.666667
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product,8076.166667
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development,5041.666667
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales,10829.083333

In [81]:
 # Compare df['Salary'] and df[['Salary']]. Print the type and shape of both.
# s = df["Salary"]
# print(type(s))
# print(s.shape)

d = df[["Salary"]]
print(type(d))
print(d.shape)

<class 'pandas.DataFrame'>
(1000, 1)

In [87]:
 # Create a new DataFrame emp_small with First Name, Gender, Team, Salary and Bonus %.
emp_small = df[["First Name", "Gender", "Team", "Salary", "Bonus %"]]
print(emp_small)

    First Name  Gender                  Team  Salary  Bonus %
0      Douglas    Male             Marketing   97308    6.945
1       Thomas    Male                   NaN   61933    4.170
2        Maria  Female               Finance  130590   11.858
3        Jerry    Male               Finance  138705    9.340
4        Larry    Male       Client Services  101004    1.389
..         ...     ...                   ...     ...      ...
995      Henry     NaN          Distribution  132483   16.655
996    Phillip    Male               Finance   42392   19.675
997    Russell    Male               Product   96914    1.421
998      Larry    Male  Business Development   60500   11.985
999     Albert    Male                 Sales  129949   10.169

[1000 rows x 5 columns]

In [89]:
df.loc[0:7]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team,Monthly Salary
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing,8109.000000
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN,5161.083333
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance,10882.500000
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance,11558.750000
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services,8417.000000
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal,9596.916667
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product,5456.333333
7,NaN,Female,7/20/2015,10:43 AM,45906,11.598,NaN,Finance,3825.500000

In [112]:
df[["Salary", "Bonus %"]].describe().loc['max', 'Bonus %']

np.float64(19.944)

In [109]:
df["Salary"].mean()

np.float64(90662.181)

In [128]:
# sal = df['Salary'].quantile(0.25)

desc = df[['Salary', "Bonus %"]].describe()
sal_25 = desc.loc['25%', 'Salary']
sal_75 = desc.loc['75%', 'Salary']

print("Salary 25%", sal_25)
print("Salary 75%", sal_75)

print("----- IQR -----")
iqr = sal_75 - sal_25
print(iqr)

Salary 25% 62613.0
Salary 75% 118740.25
----- IQR -----
56127.25

In [134]:
max = df["Salary"].max()
min = df["Salary"].min()

print(max - min)

114895

In [140]:
df.iloc[24, 0]

'John'

In [142]:
df.loc[99, "Team"]

'Business Development'

In [158]:
df["Salary"].iloc[-1]

np.int64(129949)

In [165]:
highest_paid = df.loc[df["Salary"].idxmax()]
print(highest_paid)

First Name              Katherine
Gender                     Female
Start Date              8/13/1996
Last Login Time          12:21 AM
Salary                     149908
Bonus %                    18.912
Senior Management           False
Team                      Finance
Monthly Salary       12492.333333
Name: 644, dtype: object